[platformio]
default_envs = wemos_d1_mini32

[env:wemos_d1_mini32]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
upload_protocol = esptool
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200
upload_speed = 115200
upload_flags =
  --before
  no_reset
  --after
  no_reset
lib_deps =
  bblanchon/ArduinoJson @ ^7.4.2
  beegee-tokyo/DHT sensor library for ESPx @ ^1.19
build_flags =
  -DCORE_DEBUG_LEVEL=1
