using System.ComponentModel;
using System.Reflection;
using Microsoft.Maui.Storage;

namespace Vendomat.Controller.Client.Localization;

public sealed class LanguageService : INotifyPropertyChanged
{
    private const string PreferenceKey = "vendomat.language";
    private readonly Dictionary<string, AppLanguageStrings> _languages = CreateLanguages();
    private string _currentLocale = "ro-RO";
    private AppLanguageStrings _lang = new();

    public LanguageService()
    {
        Current = this;
        AvailableLanguages =
        [
            new LanguageOption("ro-RO", "Rom\u00E2n\u0103", "ro.svg", "RO"),
            new LanguageOption("hu-HU", "Magyar", "hu.svg", "HU"),
            new LanguageOption("en-US", "English", "us.svg", "US"),
        ];

        Load();
    }

    public static LanguageService? Current { get; private set; }

    public event PropertyChangedEventHandler? PropertyChanged;

    public event EventHandler? LanguageChanged;

    public IReadOnlyList<LanguageOption> AvailableLanguages { get; }

    public string CurrentLocale
    {
        get => _currentLocale;
        private set
        {
            if (_currentLocale == value)
            {
                return;
            }

            _currentLocale = value;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(CurrentLocale)));
        }
    }

    public AppLanguageStrings Lang
    {
        get => _lang;
        private set
        {
            _lang = value;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Lang)));
        }
    }

    public void Load()
    {
        var locale = Preferences.Default.Get(PreferenceKey, "ro-RO");
        ApplyLanguage(locale, persist: false);
    }

    public bool SetLanguage(string? locale)
    {
        if (string.IsNullOrWhiteSpace(locale))
        {
            return false;
        }

        return ApplyLanguage(locale, persist: true);
    }

    public string GetText(string propertyName)
    {
        var property = typeof(AppLanguageStrings).GetRuntimeProperty(propertyName);
        return property?.GetValue(Lang)?.ToString() ?? $"[{propertyName}]";
    }

    public LanguageOption GetCurrentLanguageOption() =>
        AvailableLanguages.FirstOrDefault(option => option.Code == CurrentLocale)
        ?? AvailableLanguages[0];

    private bool ApplyLanguage(string locale, bool persist)
    {
        if (!_languages.TryGetValue(locale, out var language))
        {
            locale = "ro-RO";
            language = _languages[locale];
        }

        var changed = CurrentLocale != locale;
        CurrentLocale = locale;
        Lang = language;

        if (persist)
        {
            Preferences.Default.Set(PreferenceKey, locale);
        }

        if (changed)
        {
            LanguageChanged?.Invoke(this, EventArgs.Empty);
        }

        return changed;
    }

    private static Dictionary<string, AppLanguageStrings> CreateLanguages() => new()
    {
        ["ro-RO"] = CreateRomanian(),
        ["hu-HU"] = CreateHungarian(),
        ["en-US"] = CreateEnglish(),
    };

    private static AppLanguageStrings CreateRomanian() => new()
    {
        CommonBack = "\u00CEnapoi",
        CommonSave = "Salveaz\u0103",
        CommonRefresh = "Actualizeaz\u0103",
        CommonCancel = "Anuleaz\u0103",
        CommonConfirm = "Confirm\u0103",
        CommonClear = "Cur\u0103\u021B\u0103",
        CommonDelete = "\u0218terge",
        DashboardSubtitle = "Controller local pentru v\u00E2nzare de lapte crud",
        DashboardPromoPlaceholder = "Aici putem \u00EEnc\u0103rca ulterior imagini reale, video sau bannere.",
        DashboardStatusTitle = "Stare controller",
        DashboardStockTitle = "Stoc curent",
        DashboardTemperatureTitle = "Temperatur\u0103",
        DashboardTemperatureSubtitle = "Monitorizare continu\u0103 ESP32",
        DashboardPriceTitle = "Pre\u021B pe litru",
        DashboardCreditTitle = "Credit curent",
        DashboardPaymentCash = "Numerar",
        DashboardPaymentCard = "Card",
        DashboardRequestedLitersTitle = "Cantitate selectat\u0103",
        DashboardSelectedTotalFormat = "Total: {0:0.00} RON",
        DashboardStockCapacityFormat = "din {0:0.##} L",
        DashboardContactFormat = "Contact operator: {0}",
        DashboardContactMissing = "Date de contact neconfigurate",
        DashboardStartDispense = "Start dozare",
        DashboardDispensingButton = "Se dozeaz\u0103...",
        DashboardStatusStarting = "Pornire controller...",
        DashboardStatusCashSelected = "Numerarul este activ. Cantitatea va urma creditul introdus.",
        DashboardStatusCardSelected = "Cardul este activ. Selecteaz\u0103 cantitatea dorit\u0103.",
        DashboardStatusDispenseStarted = "Dozarea a fost pornit\u0103.",
        DashboardStatusDispensing = "Se dozeaz\u0103 laptele. Te rug\u0103m s\u0103 p\u0103strezi recipientul fix.",
        DashboardStatusCleaning = "Controllerul execut\u0103 ciclul de cur\u0103\u021Bare.",
        DashboardStatusCashBlocked = "Numerar detectat. Plata cu cardul este blocat\u0103 pentru sesiunea curent\u0103.",
        DashboardStatusCashReady = "Numerarul este activ. Introdu bancnotele, iar cantitatea se calculeaz\u0103 automat.",
        DashboardStatusReady = "Controller gata de servire.",
        DashboardAdminUnlockTitle = "Acces administrator",
        DashboardAdminUnlockSubtitle = "Introdu codul numeric pentru a deschide set\u0103rile controllerului.",
        DashboardAdminUnlockPlaceholder = "Introdu codul de acces",
        DashboardAdminUnlockInvalid = "Cod incorect. \u00CEncearc\u0103 din nou.",
        DashboardAdminChangeRequired = "Codul implicit 1234 este blocat. Alege un cod administrator nou.",
        DashboardAdminChangeConfirm = "Confirm\u0103 noul cod administrator.",
        DashboardAdminChangeMismatch = "Codurile nu coincid. Reintrodu codul nou.",
        DashboardAdminChangeTooShort = "Codul nou trebuie s\u0103 aib\u0103 minimum 4 cifre.",
        DashboardAdminChangeDigitsOnly = "Codul nou poate con\u021Bine doar cifre.",
        DashboardAdminDefaultPasscodeBlocked = "Codul 1234 nu mai poate fi folosit.",
        SettingsTitle = "Set\u0103ri controller",
        SettingsSalesTab = "V\u00E2nzare",
        SettingsGeneralSection = "General",
        SettingsSalesCardTitle = "Parametri de v\u00E2nzare",
        SettingsSalesCardDescription = "Configureaz\u0103 numele dozatorului, pre\u021Bul, impulsurile debitmetrului \u0219i stocul disponibil.",
        SettingsAdminSection = "Acces administrator",
        SettingsAdminCardDescription = "Schimb\u0103 parola secret\u0103 pentru accesul local \u00EEn set\u0103ri. Las\u0103 c\u00E2mpurile goale dac\u0103 nu vrei s\u0103 o modifici.",
        SettingsPaymentSection = "Plat\u0103 \u0219i contact",
        SettingsPaymentCardDescription = "Activeaz\u0103 metodele de plat\u0103 care trebuie afi\u0219ate clientului pe ecranul principal.",
        SettingsContactCardTitle = "Date afi\u0219ate clientului",
        SettingsContactCardDescription = "Aceste date apar pe ecranul vendomatului \u0219i ajut\u0103 clientul s\u0103 contacteze operatorul.",
        SettingsValidatorSection = "Validator bancnote",
        SettingsValidatorCardDescription = "Configureaz\u0103 comunicarea SSP/NV9 \u0219i modul \u00EEn care controllerul decide acceptarea bancnotelor.",
        SettingsValidatorChannelsTitle = "Bancnote acceptate",
        SettingsValidatorChannelsDescription = "Activeaz\u0103 doar valorile pe care validatorul trebuie s\u0103 le accepte pentru sesiunea de v\u00E2nzare.",
        SettingsEsp32Section = "ESP32 \u0219i senzori",
        SettingsEsp32CardDescription = "Seteaz\u0103 portul \u0219i strategia de conectare pentru ESP32-ul care cite\u0219te senzorii \u0219i controleaz\u0103 pompa.",
        SettingsCleaningSection = "Cur\u0103\u021Bare",
        SettingsCleaningCardDescription = "Ruleaz\u0103 manual ciclurile de sp\u0103lare pentru tubulatur\u0103 \u0219i pomp\u0103.",
        SettingsUpdatesSection = "Update-uri",
        SettingsUpdatesCardDescription = "Arat\u0103 ce componente pot fi actualizate din ecosistemul local al controllerului.",
        SettingsUpdatesAvailableStatus = "Disponibil",
        SettingsUpdatesControlTitle = "Aplica\u021Bia de control",
        SettingsUpdatesControlDescription = "Tableta poate primi un update nou al aplica\u021Biei de control prin pachet Android semnat.",
        SettingsUpdatesControlVersionFormat = "Versiune curent\u0103: {0}",
        SettingsUpdatesEsp32Title = "Firmware ESP32",
        SettingsUpdatesEsp32Description = "Controllerul poate trimite update OTA c\u0103tre ESP32 prin fluxul serial \u0219i re\u021Beaua Wi-Fi.",
        SettingsContinuousCleaningDescription = "Porne\u0219te pompa continuu pentru o cl\u0103tire rapid\u0103 a circuitului.",
        SettingsPulsedCleaningDescription = "Alterneaz\u0103 pornirea \u0219i oprirea pompei pentru o cur\u0103\u021Bare mai agresiv\u0103.",
        SettingsPairingSection = "Pairing aplica\u021Bie mobil\u0103",
        SettingsPairingCardDescription = "Configureaz\u0103 identitatea dozatorului \u0219i adresele folosite de aplica\u021Bia companion \u00EEn re\u021Beaua local\u0103 sau prin internet.",
        SettingsPairingSecurityHint = "QR-ul con\u021Bine Machine ID-ul unic al dozatorului, iar aplica\u021Bia prime\u0219te apoi un token securizat pentru acces remote.",
        SettingsPairingCodeTitle = "Cod de \u00EEmperechere",
        SettingsPairingEndpointTitle = "Endpoint principal pentru companion",
        SettingsMachineIdLabel = "Machine ID unic",
        SettingsLocalApiBaseUrlLabel = "Adres\u0103 API local\u0103",
        SettingsPublicApiBaseUrlLabel = "Adres\u0103 API public\u0103",
        SettingsCloudApiBaseUrlLabel = "Adres\u0103 cloud broker",
        SettingsMachineNamePlaceholder = "Nume vendomat",
        SettingsPricePlaceholder = "Pre\u021B / litru",
        SettingsPulsesPlaceholder = "Impulsuri / litru",
        SettingsCurrentStockPlaceholder = "Stoc curent",
        SettingsTankCapacityPlaceholder = "Capacitate rezervor",
        SettingsLowStockPlaceholder = "Prag alert\u0103 stoc",
        SettingsCashPayment = "Plat\u0103 numerar",
        SettingsCardPayment = "Plat\u0103 card",
        SettingsContactPhonePlaceholder = "Telefon contact",
        SettingsContactEmailPlaceholder = "Email contact",
        SettingsApiBaseUrlPlaceholder = "http://vendomat.local:1326",
        SettingsPublicApiBaseUrlPlaceholder = "https://milk-01.example.com",
        SettingsCloudApiBaseUrlPlaceholder = "https://vending.dllsoft.ro",
        SettingsValidatorEnabled = "Validator activ",
        SettingsValidatorEscrow = "Escrow host control",
        SettingsBillPortLabel = "Port validator",
        SettingsBillBaudLabel = "Baud rate validator",
        SettingsBillPortPlaceholder = "/dev/ttyACM0",
        SettingsBillBaudPlaceholder = "115200",
        SettingsEsp32Enabled = "ESP32 activ",
        SettingsEsp32AutoDiscover = "Autodetec\u021Bie port",
        SettingsRuntimeDemoMode = "Mod demo",
        SettingsRuntimeDemoModeHint = "Finalizeaz\u0103 dozarea prin simulare doar pentru test, f\u0103r\u0103 confirmare ESP32.",
        SettingsEsp32PortLabel = "Port ESP32",
        SettingsEsp32BaudLabel = "Baud rate ESP32",
        SettingsEsp32PortPlaceholder = "/dev/ttyS3",
        SettingsEsp32BaudPlaceholder = "115200",
        SettingsContinuousCleaning = "Cur\u0103\u021Bare continu\u0103",
        SettingsPulsedCleaning = "Cur\u0103\u021Bare pulsat\u0103",
        SettingsGenerateQr = "Genereaz\u0103 cod QR",
        SettingsAdminPasscodePlaceholder = "Parol\u0103 nou\u0103 administrator",
        SettingsAdminPasscodeConfirmPlaceholder = "Confirm\u0103 parola nou\u0103",
        SettingsAdminPasscodeHint = "Las\u0103 c\u00E2mpurile goale dac\u0103 vrei s\u0103 p\u0103strezi parola curent\u0103.",
        SettingsPairingCodeFormat = "Cod: {0}",
        SettingsPairingEndpointFormat = "Endpoint: {0}",
        SettingsSaveButton = "Salveaz\u0103 set\u0103rile",
        SettingsLoadingStatus = "\u00CEncarc set\u0103rile controllerului...",
        SettingsReadyStatus = "Set\u0103rile sunt gata pentru editare.",
        SettingsSavedStatus = "Set\u0103rile au fost salvate local pe tablet\u0103.",
        SettingsAdminPasscodeUpdatedStatus = "Set\u0103rile au fost salvate, iar parola administratorului a fost actualizat\u0103.",
        SettingsAdminPasscodeDigitsOnlyStatus = "Parola administratorului poate con\u021Bine doar cifre.",
        SettingsAdminPasscodeTooShortStatus = "Parola administratorului trebuie s\u0103 aib\u0103 minimum 4 cifre.",
        SettingsAdminPasscodeDefaultRejectedStatus = "Parola implicit\u0103 1234 nu mai poate fi folosit\u0103.",
        SettingsAdminPasscodeMismatchStatus = "Parola nou\u0103 \u0219i confirmarea nu coincid.",
        SettingsQrReadyStatus = "Codul de pairing este gata pentru aplica\u021Bia mobil\u0103.",
        SettingsContinuousCleaningStatus = "Cur\u0103\u021Barea continu\u0103 a fost executat\u0103.",
        SettingsPulsedCleaningStatus = "Cur\u0103\u021Barea pulsat\u0103 a fost executat\u0103.",
        MobileDevicesTitle = "Dozatoarele mele",
        MobileDevicesSubtitle = "Monitorizeaz\u0103 \u0219i configureaz\u0103 mai multe vendomate dintr-un singur loc.",
        MobileAddDevice = "Adaug\u0103 prin QR",
        MobileDevicesEmptyTitle = "Niciun dozator \u00EEmperecheat",
        MobileDevicesEmptySubtitle = "Scaneaz\u0103 codul QR afi\u0219at pe vendomat pentru a-l ad\u0103uga \u00EEn aplica\u021Bie.",
        MobileDevicesOpenDashboard = "Dashboard",
        MobileDevicesOpenSettings = "Set\u0103ri",
        MobileDevicesRemoveTitle = "\u0218terge dozatorul",
        MobileDevicesRemoveMessageFormat = "Vrei s\u0103 elimini dozatorul \"{0}\" din aplica\u021Bia companion?",
        MobileDevicesStatusOnline = "Online",
        MobileDevicesStatusOffline = "Offline",
        MobileDevicesLastSeenFormat = "Ultima actualizare: {0:g}",
        MobileScannerTitle = "Scaneaz\u0103 codul QR",
        MobileScannerSubtitle = "\u00CEndreapt\u0103 camera c\u0103tre codul afi\u0219at pe ecranul dozatorului.",
        MobileScannerManualHint = "Dac\u0103 scanarea nu porne\u0219te, verific\u0103 permisiunea de camer\u0103.",
        MobileScannerManualModeTitle = "Imperechere manual\u0103",
        MobileScannerManualModeHint = "Mod ascuns pentru test: completeaz\u0103 datele de pairing sau porne\u0219te-l prin ADB.",
        MobileScannerManualOpenStatus = "Modul manual de imperechere a fost deschis.",
        MobileScannerManualPairButton = "Imperecheaz\u0103 manual",
        MobileScannerManualInvalidData = "Datele de imperechere manual\u0103 sunt incomplete sau invalide.",
        MobileScannerInvalidQr = "Codul QR nu con\u021Bine un payload valid pentru vendomat.",
        MobileScannerExpiredQr = "Codul QR a expirat. Genereaz\u0103 unul nou din controller.",
        MobileScannerPermissionRequired = "Permisiunea camerei este necesar\u0103 pentru scanarea codului QR.",
        MobileScannerConnectionError = "Nu am putut contacta dozatorul pe niciun endpoint valid din QR, inclusiv brokerul cloud.",
        MobileScannerPairSuccess = "Dozatorul a fost ad\u0103ugat \u00EEn aplica\u021Bie.",
        MobileScannerAlreadyAdded = "Acest dozator exist\u0103 deja \u00EEn aplica\u021Bie.",
        MobileDetailStatusTitle = "Stare curent\u0103",
        MobileDetailTemperatureTitle = "Temperatur\u0103",
        MobileDetailStockTitle = "Stoc",
        MobileDetailPriceTitle = "Pre\u021B pe litru",
        MobileDetailCreditTitle = "Credit curent",
        MobileDetailPaymentTitle = "Plat\u0103 activ\u0103",
        MobileDetailStateTitle = "Activitate",
        MobileDetailContactTitle = "Contact",
        MobileDetailApiBaseUrlTitle = "API",
        MobileDetailOpenSettings = "Deschide set\u0103rile",
        MobileDetailRemoteCreditTitle = "Credit remote",
        MobileDetailRemoteCreditSubtitle = "Adaug\u0103 rapid credit \u00EEn sesiunea curent\u0103 direct din aplica\u021Bia companion.",
        MobileDetailRemoteCreditButton = "Adaug\u0103 credit",
        MobileDetailRemoteCreditInvalid = "Introdu o sum\u0103 valid\u0103 pentru creditul remote.",
        MobileDetailRemoteCreditError = "Nu am putut ad\u0103uga creditul remote. Verific\u0103 endpoint-ul activ \u0219i conexiunea dozatorului.",
        MobileDetailRemoteCreditQueued = "Comanda a fost trimis\u0103 prin cloud \u0219i va fi aplicat\u0103 pe dozator \u00EEn c\u00E2teva secunde.",
        MobileDetailRunContinuousCleaning = "Cur\u0103\u021Bare continu\u0103",
        MobileDetailRunPulsedCleaning = "Cur\u0103\u021Bare pulsat\u0103",
        MobileDetailUpdatedAtFormat = "Actualizat la {0:g}",
        MobileDetailSalesSectionTitle = "V\u00E2nz\u0103ri",
        MobileDetailTodayRevenueTitle = "Venit ast\u0103zi",
        MobileDetailTodaySalesCountTitle = "V\u00E2nz\u0103ri ast\u0103zi",
        MobileDetailTotalRevenueTitle = "Venit total",
        MobileDetailTotalSalesCountTitle = "Total tranzac\u021Bii",
        MobileDetailRecentSalesTitle = "Istoric v\u00E2nz\u0103ri",
        MobileDetailNoSalesHistory = "Nu exist\u0103 \u00EEnc\u0103 v\u00E2nz\u0103ri salvate pentru acest dozator.",
        MobileDetailSanitationSectionTitle = "Igienizare",
        MobileDetailLastSanitationTitle = "Ultima igienizare",
        MobileDetailSanitationCountTitle = "Cicluri",
        MobileDetailRecentSanitationTitle = "Istoric igienizare",
        MobileDetailNoSanitationHistory = "Nu exist\u0103 \u00EEnc\u0103 cicluri de igienizare salvate.",
        MobileDetailSaleStatusPending = "\u00CEn a\u0219teptare",
        MobileDetailSaleStatusCompleted = "Finalizat\u0103",
        MobileDetailSaleStatusFailed = "E\u0219uat\u0103",
        MobileDetailSanitationContinuous = "Cur\u0103\u021Bare continu\u0103",
        MobileDetailSanitationPulsed = "Cur\u0103\u021Bare pulsat\u0103",
        MobileDetailReady = "Gata",
        MobileDetailDispensing = "Dozare \u00EEn curs",
        MobileDetailCleaning = "Cur\u0103\u021Bare \u00EEn curs",
        MobileDetailOutOfService = "Scos din func\u021Biune",
        MobileDetailUnknown = "Necunoscut",
        MobileSettingsTitle = "Set\u0103ri dozator",
        MobileSettingsStatusLoading = "\u00CEncarc set\u0103rile dispozitivului...",
        MobileSettingsStatusLoaded = "Set\u0103rile remote sunt gata pentru editare.",
        MobileSettingsStatusSending = "Trimit modific\u0103rile c\u0103tre dozator...",
        MobileSettingsStatusAwaitingDevice = "A\u0219tept confirmarea din dozator...",
        MobileSettingsStatusApplied = "Dozatorul a aplicat set\u0103rile \u0219i le-a confirmat.",
        MobileSettingsStatusSaved = "Set\u0103rile remote au fost salvate.",
        MobileSettingsStatusLoadError = "Nu am putut \u00EEnc\u0103rca set\u0103rile de la dozator.",
        MobileSettingsStatusSaveError = "Nu am putut salva set\u0103rile pe dozator.",
        MobileConnectionSectionTitle = "Conectare companion",
        MobileConnectionSectionSubtitle = "Alege cum \u00EEncearc\u0103 telefonul s\u0103 ajung\u0103 la vendomat \u0219i vezi imediat ruta activ\u0103.",
        MobileConnectionStrategyTitle = "Strategie",
        MobileConnectionActiveModeTitle = "Rut\u0103 activ\u0103",
        MobileConnectionActiveEndpointTitle = "Endpoint activ",
        MobileConnectionFallbackTitle = "Ordine fallback",
        MobileConnectionModeAutoTitle = "Auto inteligent",
        MobileConnectionModeAutoDescription = "\u00CEncearc\u0103 mai \u00EEnt\u00E2i conexiunea local\u0103 dac\u0103 telefonul este \u00EEn aceea\u0219i re\u021Bea, apoi endpointul public, apoi bridge-ul cloud.",
        MobileConnectionModeLocalTitle = "Local mai \u00EEnt\u00E2i",
        MobileConnectionModeLocalDescription = "Prefer\u0103 API-ul local c\u00E2nd e\u0219ti l\u00E2ng\u0103 vendomat, apoi \u00EEncearc\u0103 direct/public \u0219i la final bridge cloud.",
        MobileConnectionModeDirectTitle = "Internet direct",
        MobileConnectionModeDirectDescription = "Prefer\u0103 endpointul public sau tunelul HTTPS. Dac\u0103 nu r\u0103spunde, cade pe bridge cloud.",
        MobileConnectionModeBridgeTitle = "Bridge cloud",
        MobileConnectionModeBridgeDescription = "Folose\u0219te doar conexiunea asistat\u0103 de server c\u00E2nd vrei acces stabil prin internet sau NAT dificil.",
        MobileConnectionActiveUnknown = "Necunoscut",
        MobileConnectionActiveLocal = "LAN local",
        MobileConnectionActiveDirect = "Direct internet",
        MobileConnectionActiveBridge = "Bridge cloud",
        MobileConnectionLocalDetected = "Re\u021Bea local\u0103 detectat\u0103: API-ul local poate fi \u00EEncercat primul.",
        MobileConnectionLocalNotDetected = "Telefonul nu pare \u00EEn aceea\u0219i re\u021Bea local\u0103: folosesc rutele remote ca fallback principal.",
        MobileConnectionEndpointMissing = "Niciun endpoint activ \u00EEnc\u0103.",
    };

    private static AppLanguageStrings CreateHungarian() => new()
    {
        CommonBack = "Vissza",
        CommonSave = "Ment\u00E9s",
        CommonRefresh = "Friss\u00EDt\u00E9s",
        CommonCancel = "M\u00E9gse",
        CommonConfirm = "Meger\u0151s\u00EDt\u00E9s",
        CommonClear = "T\u00F6rl\u00E9s",
        CommonDelete = "T\u00F6rl\u00E9s",
        DashboardSubtitle = "Helyi vez\u00E9rl\u0151 nyerstej adagol\u00E1s\u00E1hoz",
        DashboardPromoPlaceholder = "Ide k\u00E9s\u0151bb val\u00F3di k\u00E9pek, vide\u00F3k vagy bannerek t\u00F6lthet\u0151k fel.",
        DashboardStatusTitle = "Vez\u00E9rl\u0151 \u00E1llapota",
        DashboardStockTitle = "Jelenlegi k\u00E9szlet",
        DashboardTemperatureTitle = "H\u0151m\u00E9rs\u00E9klet",
        DashboardTemperatureSubtitle = "Folyamatos ESP32 fel\u00FCgyelet",
        DashboardPriceTitle = "Literenk\u00E9nti \u00E1r",
        DashboardCreditTitle = "Aktu\u00E1lis egyenleg",
        DashboardPaymentCash = "K\u00E9szp\u00E9nz",
        DashboardPaymentCard = "K\u00E1rtya",
        DashboardRequestedLitersTitle = "Kiv\u00E1lasztott mennyis\u00E9g",
        DashboardSelectedTotalFormat = "\u00D6sszesen: {0:0.00} RON",
        DashboardStockCapacityFormat = "ebb\u0151l {0:0.##} L",
        DashboardContactFormat = "\u00DCzemeltet\u0151 el\u00E9rhet\u0151s\u00E9ge: {0}",
        DashboardContactMissing = "Nincs be\u00E1ll\u00EDtott el\u00E9rhet\u0151s\u00E9g",
        DashboardStartDispense = "Adagol\u00E1s ind\u00EDt\u00E1sa",
        DashboardDispensingButton = "Adagol\u00E1s...",
        DashboardStatusStarting = "A vez\u00E9rl\u0151 indul...",
        DashboardStatusCashSelected = "A k\u00E9szp\u00E9nzes fizet\u00E9s akt\u00EDv. A mennyis\u00E9g a bevitt egyenleghez igazodik.",
        DashboardStatusCardSelected = "A k\u00E1rty\u00E1s fizet\u00E9s akt\u00EDv. V\u00E1laszd ki a k\u00EDv\u00E1nt mennyis\u00E9get.",
        DashboardStatusDispenseStarted = "Az adagol\u00E1s elindult.",
        DashboardStatusDispensing = "A tej adagol\u00E1sa folyamatban van. K\u00E9rj\u00FCk, tartsd stabilan a palackot.",
        DashboardStatusCleaning = "A vez\u00E9rl\u0151 tiszt\u00EDt\u00E1si ciklust futtat.",
        DashboardStatusCashBlocked = "K\u00E9szp\u00E9nz \u00E9rz\u00E9kelve. A k\u00E1rty\u00E1s fizet\u00E9s ehhez a munkamenethez le van tiltva.",
        DashboardStatusCashReady = "A k\u00E9szp\u00E9nzes fizet\u00E9s akt\u00EDv. Helyezd be a bankjegyeket, a mennyis\u00E9g automatikusan sz\u00E1mol\u00F3dik.",
        DashboardStatusReady = "A vez\u00E9rl\u0151 kiszolg\u00E1l\u00E1sra k\u00E9sz.",
        DashboardAdminUnlockTitle = "Adminisztr\u00E1tori hozz\u00E1f\u00E9r\u00E9s",
        DashboardAdminUnlockSubtitle = "Add meg a sz\u00E1mk\u00F3dot a vez\u00E9rl\u0151 be\u00E1ll\u00EDt\u00E1sainak megnyit\u00E1s\u00E1hoz.",
        DashboardAdminUnlockPlaceholder = "Add meg a bel\u00E9p\u00E9si k\u00F3dot",
        DashboardAdminUnlockInvalid = "Hib\u00E1s k\u00F3d. Pr\u00F3b\u00E1ld \u00FAjra.",
        DashboardAdminChangeRequired = "Az alap\u00E9rtelmezett 1234 k\u00F3d tiltva van. V\u00E1lassz \u00FAj admin k\u00F3dot.",
        DashboardAdminChangeConfirm = "Er\u0151s\u00EDtsd meg az \u00FAj admin k\u00F3dot.",
        DashboardAdminChangeMismatch = "A k\u00F3dok nem egyeznek. Add meg \u00FAjra az \u00FAj k\u00F3dot.",
        DashboardAdminChangeTooShort = "Az \u00FAj k\u00F3d legal\u00E1bb 4 sz\u00E1mjegyb\u0151l \u00E1lljon.",
        DashboardAdminChangeDigitsOnly = "Az \u00FAj k\u00F3d csak sz\u00E1mjegyeket tartalmazhat.",
        DashboardAdminDefaultPasscodeBlocked = "Az 1234 k\u00F3d m\u00E1r nem haszn\u00E1lhat\u00F3.",
        SettingsTitle = "Vez\u00E9rl\u0151 be\u00E1ll\u00EDt\u00E1sai",
        SettingsSalesTab = "\u00C9rt\u00E9kes\u00EDt\u00E9s",
        SettingsGeneralSection = "\u00C1ltal\u00E1nos",
        SettingsSalesCardTitle = "\u00C9rt\u00E9kes\u00EDt\u00E9si param\u00E9terek",
        SettingsSalesCardDescription = "\u00C1ll\u00EDtsd be az automata nev\u00E9t, az \u00E1rat, a literenk\u00E9nti impulzusokat \u00E9s a rendelkez\u00E9sre \u00E1ll\u00F3 k\u00E9szletet.",
        SettingsAdminSection = "Adminisztr\u00E1tori hozz\u00E1f\u00E9r\u00E9s",
        SettingsAdminCardDescription = "M\u00F3dos\u00EDtsd a helyi be\u00E1ll\u00EDt\u00E1sokhoz tartoz\u00F3 titkos k\u00F3dot. Hagyd \u00FCresen a mez\u0151ket, ha nem szeretn\u00E9d megv\u00E1ltoztatni.",
        SettingsPaymentSection = "Fizet\u00E9s \u00E9s kapcsolat",
        SettingsPaymentCardDescription = "Kapcsold be azokat a fizet\u00E9si m\u00F3dokat, amelyek a f\u0151k\u00E9perny\u0151n megjelenjenek a v\u00E1s\u00E1rl\u00F3nak.",
        SettingsContactCardTitle = "Vev\u0151nek megjelen\u0151 adatok",
        SettingsContactCardDescription = "Ezek az adatok az automata kijelz\u0151j\u00E9n jelennek meg, hogy a v\u00E1s\u00E1rl\u00F3 el tudja \u00E9rni az \u00FCzemeltet\u0151t.",
        SettingsValidatorSection = "Bankjegyelfogad\u00F3",
        SettingsValidatorCardDescription = "\u00C1ll\u00EDtsd be az SSP/NV9 kapcsolatot \u00E9s azt, hogyan d\u00F6nts\u00F6n a vez\u00E9rl\u0151 a bankjegyek elfogad\u00E1s\u00E1r\u00F3l.",
        SettingsValidatorChannelsTitle = "Elfogadott bankjegyek",
        SettingsValidatorChannelsDescription = "Csak azokat az \u00E9rt\u00E9keket kapcsold be, amelyeket az elfogad\u00F3nak engednie kell az elad\u00E1si folyamatban.",
        SettingsEsp32Section = "ESP32 \u00E9s szenzorok",
        SettingsEsp32CardDescription = "\u00C1ll\u00EDtsd be a portot \u00E9s a kapcsol\u00F3d\u00E1si strat\u00E9gi\u00E1t ahhoz az ESP32-h\u00F6z, amely a szenzorokat olvassa \u00E9s a szivatty\u00FAt vez\u00E9rli.",
        SettingsCleaningSection = "Tiszt\u00EDt\u00E1s",
        SettingsCleaningCardDescription = "Futtasd manu\u00E1lisan a cs\u0151rendszer \u00E9s a szivatty\u00FA tiszt\u00EDt\u00E1si ciklusait.",
        SettingsUpdatesSection = "Friss\u00EDt\u00E9sek",
        SettingsUpdatesCardDescription = "Megmutatja, mely komponensek friss\u00EDthet\u0151k a vez\u00E9rl\u0151 helyi \u00F6kosziszt\u00E9m\u00E1j\u00E1ban.",
        SettingsUpdatesAvailableStatus = "El\u00E9rhet\u0151",
        SettingsUpdatesControlTitle = "Vez\u00E9rl\u0151 alkalmaz\u00E1s",
        SettingsUpdatesControlDescription = "A tablet kaphat \u00FAj vez\u00E9rl\u0151 alkalmaz\u00E1s friss\u00EDt\u00E9st al\u00E1\u00EDrt Android csomaggal.",
        SettingsUpdatesControlVersionFormat = "Jelenlegi verzi\u00F3: {0}",
        SettingsUpdatesEsp32Title = "ESP32 firmware",
        SettingsUpdatesEsp32Description = "A vez\u00E9rl\u0151 OTA friss\u00EDt\u00E9st tud k\u00FCldeni az ESP32-nek soros kapcsolaton \u00E9s Wi-Fi-n kereszt\u00FCl.",
        SettingsContinuousCleaningDescription = "Folyamatosan ind\u00EDtja a szivatty\u00FAt a gyors \u00F6bl\u00EDt\u00E9shez.",
        SettingsPulsedCleaningDescription = "V\u00E1ltogatja a szivatty\u00FA be- \u00E9s kikapcsol\u00E1s\u00E1t az er\u0151sebb tiszt\u00EDt\u00E1s \u00E9rdek\u00E9ben.",
        SettingsPairingSection = "Mobilalkalmaz\u00E1s p\u00E1ros\u00EDt\u00E1sa",
        SettingsPairingCardDescription = "\u00C1ll\u00EDtsd be az automata egyedi azonos\u00EDt\u00F3j\u00E1t \u00E9s azokat a c\u00EDmeket, amelyeket a companion alkalmaz\u00E1s helyi h\u00E1l\u00F3zaton vagy interneten kereszt\u00FCl haszn\u00E1l.",
        SettingsPairingSecurityHint = "A QR-k\u00F3d tartalmazza az automata egyedi Machine ID-j\u00E1t, a companion alkalmaz\u00E1s pedig ezut\u00E1n biztons\u00E1gos t\u00E1voli tokent kap.",
        SettingsPairingCodeTitle = "P\u00E1ros\u00EDt\u00E1si k\u00F3d",
        SettingsPairingEndpointTitle = "Els\u0151dleges companion v\u00E9gpont",
        SettingsMachineIdLabel = "Egyedi Machine ID",
        SettingsLocalApiBaseUrlLabel = "Helyi API c\u00EDm",
        SettingsPublicApiBaseUrlLabel = "Nyilv\u00E1nos API c\u00EDm",
        SettingsCloudApiBaseUrlLabel = "Cloud broker c\u00EDm",
        SettingsMachineNamePlaceholder = "Automata neve",
        SettingsPricePlaceholder = "\u00C1r / liter",
        SettingsPulsesPlaceholder = "Impulzus / liter",
        SettingsCurrentStockPlaceholder = "Jelenlegi k\u00E9szlet",
        SettingsTankCapacityPlaceholder = "Tart\u00E1ly kapacit\u00E1sa",
        SettingsLowStockPlaceholder = "Alacsony k\u00E9szlet k\u00FCsz\u00F6b",
        SettingsCashPayment = "K\u00E9szp\u00E9nzes fizet\u00E9s",
        SettingsCardPayment = "K\u00E1rty\u00E1s fizet\u00E9s",
        SettingsContactPhonePlaceholder = "Kapcsolattart\u00F3 telefonsz\u00E1m",
        SettingsContactEmailPlaceholder = "Kapcsolattart\u00F3 e-mail",
        SettingsApiBaseUrlPlaceholder = "http://vendomat.local:1326",
        SettingsPublicApiBaseUrlPlaceholder = "https://milk-01.example.com",
        SettingsCloudApiBaseUrlPlaceholder = "https://vending.dllsoft.ro",
        SettingsValidatorEnabled = "Elfogad\u00F3 akt\u00EDv",
        SettingsValidatorEscrow = "Gazda \u00E1ltal kezelt escrow",
        SettingsBillPortLabel = "Elfogad\u00F3 port",
        SettingsBillBaudLabel = "Elfogad\u00F3 baud rate",
        SettingsBillPortPlaceholder = "/dev/ttyACM0",
        SettingsBillBaudPlaceholder = "115200",
        SettingsEsp32Enabled = "ESP32 akt\u00EDv",
        SettingsEsp32AutoDiscover = "Port automatikus felismer\u00E9se",
        SettingsRuntimeDemoMode = "Demo m\u00F3d",
        SettingsRuntimeDemoModeHint = "Csak teszthez fejezi be szimul\u00E1ci\u00F3val az adagol\u00E1st, ESP32 visszaigazol\u00E1s n\u00E9lk\u00FCl.",
        SettingsEsp32PortLabel = "ESP32 port",
        SettingsEsp32BaudLabel = "ESP32 baud rate",
        SettingsEsp32PortPlaceholder = "/dev/ttyS3",
        SettingsEsp32BaudPlaceholder = "115200",
        SettingsContinuousCleaning = "Folyamatos tiszt\u00EDt\u00E1s",
        SettingsPulsedCleaning = "Pulz\u00E1l\u00F3 tiszt\u00EDt\u00E1s",
        SettingsGenerateQr = "QR-k\u00F3d gener\u00E1l\u00E1sa",
        SettingsAdminPasscodePlaceholder = "\u00DAj admin jelsz\u00F3",
        SettingsAdminPasscodeConfirmPlaceholder = "\u00DAj jelsz\u00F3 meger\u0151s\u00EDt\u00E9se",
        SettingsAdminPasscodeHint = "Hagyd \u00FCresen a mez\u0151ket, ha meg akarod tartani a jelenlegi jelsz\u00F3t.",
        SettingsPairingCodeFormat = "K\u00F3d: {0}",
        SettingsPairingEndpointFormat = "V\u00E9gpont: {0}",
        SettingsSaveButton = "Be\u00E1ll\u00EDt\u00E1sok ment\u00E9se",
        SettingsLoadingStatus = "A vez\u00E9rl\u0151 be\u00E1ll\u00EDt\u00E1sainak bet\u00F6lt\u00E9se...",
        SettingsReadyStatus = "A be\u00E1ll\u00EDt\u00E1sok szerkeszt\u00E9sre k\u00E9szek.",
        SettingsSavedStatus = "A be\u00E1ll\u00EDt\u00E1sok helyben elmentve a tabletre.",
        SettingsAdminPasscodeUpdatedStatus = "A be\u00E1ll\u00EDt\u00E1sok mentve, az admin jelsz\u00F3 friss\u00EDtve lett.",
        SettingsAdminPasscodeDigitsOnlyStatus = "Az admin jelsz\u00F3 csak sz\u00E1mokat tartalmazhat.",
        SettingsAdminPasscodeTooShortStatus = "Az admin jelsz\u00F3nak legal\u00E1bb 4 sz\u00E1mjegyb\u0151l kell \u00E1llnia.",
        SettingsAdminPasscodeDefaultRejectedStatus = "Az alap\u00E9rtelmezett 1234 jelsz\u00F3 m\u00E1r nem haszn\u00E1lhat\u00F3.",
        SettingsAdminPasscodeMismatchStatus = "Az \u00FAj jelsz\u00F3 \u00E9s a meger\u0151s\u00EDt\u00E9s nem egyezik.",
        SettingsQrReadyStatus = "A p\u00E1ros\u00EDt\u00E1si k\u00F3d k\u00E9szen \u00E1ll a mobilalkalmaz\u00E1shoz.",
        SettingsContinuousCleaningStatus = "A folyamatos tiszt\u00EDt\u00E1s lefutott.",
        SettingsPulsedCleaningStatus = "A pulz\u00E1l\u00F3 tiszt\u00EDt\u00E1s lefutott.",
        MobileDevicesTitle = "Adagol\u00F3im",
        MobileDevicesSubtitle = "T\u00F6bb automata fel\u00FCgyelete \u00E9s konfigur\u00E1l\u00E1sa egyetlen alkalmaz\u00E1sb\u00F3l.",
        MobileAddDevice = "Hozz\u00E1ad\u00E1s QR-rel",
        MobileDevicesEmptyTitle = "Nincs p\u00E1ros\u00EDtott adagol\u00F3",
        MobileDevicesEmptySubtitle = "Olvasd be az automat\u00E1n megjelen\u0151 QR-k\u00F3dot az alkalmaz\u00E1shoz ad\u00E1shoz.",
        MobileDevicesOpenDashboard = "Dashboard",
        MobileDevicesOpenSettings = "Be\u00E1ll\u00EDt\u00E1sok",
        MobileDevicesRemoveTitle = "Adagol\u00F3 t\u00F6rl\u00E9se",
        MobileDevicesRemoveMessageFormat = "El szeretn\u00E9d t\u00E1vol\u00EDtani a(z) \"{0}\" adagol\u00F3t a companion alkalmaz\u00E1sb\u00F3l?",
        MobileDevicesStatusOnline = "Online",
        MobileDevicesStatusOffline = "Offline",
        MobileDevicesLastSeenFormat = "Utols\u00F3 friss\u00EDt\u00E9s: {0:g}",
        MobileScannerTitle = "QR-k\u00F3d beolvas\u00E1sa",
        MobileScannerSubtitle = "Ir\u00E1ny\u00EDtsd a kamer\u00E1t az adagol\u00F3 kijelz\u0151j\u00E9n l\u00E1that\u00F3 k\u00F3dra.",
        MobileScannerManualHint = "Ha a beolvas\u00E1s nem indul, ellen\u0151rizd a kameraenged\u00E9lyt.",
        MobileScannerManualModeTitle = "K\u00E9zi p\u00E1ros\u00EDt\u00E1s",
        MobileScannerManualModeHint = "Rejtett tesztm\u00F3d: add meg a p\u00E1ros\u00EDt\u00E1si adatokat vagy ind\u00EDtsd ADB-b\u0151l.",
        MobileScannerManualOpenStatus = "Megny\u00EDlt a k\u00E9zi p\u00E1ros\u00EDt\u00E1si m\u00F3d.",
        MobileScannerManualPairButton = "K\u00E9zi p\u00E1ros\u00EDt\u00E1s",
        MobileScannerManualInvalidData = "A k\u00E9zi p\u00E1ros\u00EDt\u00E1s adatai hi\u00E1nyosak vagy \u00E9rv\u00E9nytelenek.",
        MobileScannerInvalidQr = "A QR-k\u00F3d nem tartalmaz \u00E9rv\u00E9nyes automata payloadot.",
        MobileScannerExpiredQr = "A QR-k\u00F3d lej\u00E1rt. Gener\u00E1lj \u00FAjat a vez\u00E9rl\u0151b\u0151l.",
        MobileScannerPermissionRequired = "A kameraenged\u00E9ly sz\u00FCks\u00E9ges a QR-k\u00F3d beolvas\u00E1s\u00E1hoz.",
        MobileScannerConnectionError = "Nem siker\u00FClt el\u00E9rni az automat\u00E1t a QR-ben szerepl\u0151 egyetlen \u00E9rv\u00E9nyes v\u00E9gponton sem, bele\u00E9rtve a cloud brokert is.",
        MobileScannerPairSuccess = "Az adagol\u00F3 hozz\u00E1adva az alkalmaz\u00E1shoz.",
        MobileScannerAlreadyAdded = "Ez az adagol\u00F3 m\u00E1r szerepel az alkalmaz\u00E1sban.",
        MobileDetailStatusTitle = "Jelenlegi \u00E1llapot",
        MobileDetailTemperatureTitle = "H\u0151m\u00E9rs\u00E9klet",
        MobileDetailStockTitle = "K\u00E9szlet",
        MobileDetailPriceTitle = "Literenk\u00E9nti \u00E1r",
        MobileDetailCreditTitle = "Aktu\u00E1lis egyenleg",
        MobileDetailPaymentTitle = "Akt\u00EDv fizet\u00E9s",
        MobileDetailStateTitle = "Tev\u00E9kenys\u00E9g",
        MobileDetailContactTitle = "Kapcsolat",
        MobileDetailApiBaseUrlTitle = "API",
        MobileDetailOpenSettings = "Be\u00E1ll\u00EDt\u00E1sok megnyit\u00E1sa",
        MobileDetailRemoteCreditTitle = "T\u00E1voli egyenleg",
        MobileDetailRemoteCreditSubtitle = "Adj gyorsan egyenleget az aktu\u00E1lis munkamenethez k\u00F6zvetlen\u00FCl a companion alkalmaz\u00E1sb\u00F3l.",
        MobileDetailRemoteCreditButton = "Egyenleg hozz\u00E1ad\u00E1sa",
        MobileDetailRemoteCreditInvalid = "Adj meg egy \u00E9rv\u00E9nyes \u00F6sszeget a t\u00E1voli egyenleghez.",
        MobileDetailRemoteCreditError = "Nem siker\u00FClt hozz\u00E1adni a t\u00E1voli egyenleget. Ellen\u0151rizd az akt\u00EDv v\u00E9gpontot \u00E9s az adagol\u00F3 kapcsolat\u00E1t.",
        MobileDetailRemoteCreditQueued = "A parancs felh\u0151n kereszt\u00FCl elk\u00FCldve, n\u00E9h\u00E1ny m\u00E1sodpercen bel\u00FCl alkalmazva lesz az adagol\u00F3n.",
        MobileDetailRunContinuousCleaning = "Folyamatos tiszt\u00EDt\u00E1s",
        MobileDetailRunPulsedCleaning = "Pulz\u00E1l\u00F3 tiszt\u00EDt\u00E1s",
        MobileDetailUpdatedAtFormat = "Friss\u00EDtve: {0:g}",
        MobileDetailSalesSectionTitle = "\u00C9rt\u00E9kes\u00EDt\u00E9sek",
        MobileDetailTodayRevenueTitle = "Mai bev\u00E9tel",
        MobileDetailTodaySalesCountTitle = "Mai elad\u00E1sok",
        MobileDetailTotalRevenueTitle = "\u00D6sszes bev\u00E9tel",
        MobileDetailTotalSalesCountTitle = "\u00D6sszes tranzakci\u00F3",
        MobileDetailRecentSalesTitle = "\u00C9rt\u00E9kes\u00EDt\u00E9si el\u0151zm\u00E9nyek",
        MobileDetailNoSalesHistory = "Ehhez az adagol\u00F3hoz m\u00E9g nincs mentett \u00E9rt\u00E9kes\u00EDt\u00E9s.",
        MobileDetailSanitationSectionTitle = "Higi\u00E9nia",
        MobileDetailLastSanitationTitle = "Utols\u00F3 higi\u00E9nia",
        MobileDetailSanitationCountTitle = "Ciklusok",
        MobileDetailRecentSanitationTitle = "Higi\u00E9niai el\u0151zm\u00E9nyek",
        MobileDetailNoSanitationHistory = "M\u00E9g nincs mentett tiszt\u00EDt\u00E1si ciklus.",
        MobileDetailSaleStatusPending = "F\u00FCgg\u0151ben",
        MobileDetailSaleStatusCompleted = "Sikeres",
        MobileDetailSaleStatusFailed = "Sikertelen",
        MobileDetailSanitationContinuous = "Folyamatos tiszt\u00EDt\u00E1s",
        MobileDetailSanitationPulsed = "Pulz\u00E1l\u00F3 tiszt\u00EDt\u00E1s",
        MobileDetailReady = "K\u00E9sz",
        MobileDetailDispensing = "Adagol\u00E1s folyamatban",
        MobileDetailCleaning = "Tiszt\u00EDt\u00E1s folyamatban",
        MobileDetailOutOfService = "\u00DCzemen k\u00EDv\u00FCl",
        MobileDetailUnknown = "Ismeretlen",
        MobileSettingsTitle = "Adagol\u00F3 be\u00E1ll\u00EDt\u00E1sai",
        MobileSettingsStatusLoading = "Az eszk\u00F6z be\u00E1ll\u00EDt\u00E1sainak bet\u00F6lt\u00E9se...",
        MobileSettingsStatusLoaded = "A t\u00E1voli be\u00E1ll\u00EDt\u00E1sok szerkeszt\u00E9sre k\u00E9szek.",
        MobileSettingsStatusSending = "A m\u00F3dos\u00EDt\u00E1sok k\u00FCld\u00E9se az adagol\u00F3nak...",
        MobileSettingsStatusAwaitingDevice = "V\u00E1rom az adagol\u00F3 visszaigazol\u00E1s\u00E1t...",
        MobileSettingsStatusApplied = "Az adagol\u00F3 alkalmazta \u00E9s visszaigazolta a be\u00E1ll\u00EDt\u00E1sokat.",
        MobileSettingsStatusSaved = "A t\u00E1voli be\u00E1ll\u00EDt\u00E1sok elmentve.",
        MobileSettingsStatusLoadError = "Nem siker\u00FClt bet\u00F6lteni az adagol\u00F3 be\u00E1ll\u00EDt\u00E1sait.",
        MobileSettingsStatusSaveError = "Nem siker\u00FClt elmenteni a be\u00E1ll\u00EDt\u00E1sokat az adagol\u00F3ra.",
        MobileConnectionSectionTitle = "Companion kapcsolat",
        MobileConnectionSectionSubtitle = "V\u00E1laszd ki, hogyan pr\u00F3b\u00E1lja a telefon el\u00E9rni az adagol\u00F3t, \u00E9s azonnal l\u00E1sd az akt\u00EDv \u00FAtvonalat.",
        MobileConnectionStrategyTitle = "Strat\u00E9gia",
        MobileConnectionActiveModeTitle = "Akt\u00EDv \u00FAtvonal",
        MobileConnectionActiveEndpointTitle = "Akt\u00EDv v\u00E9gpont",
        MobileConnectionFallbackTitle = "Fallback sorrend",
        MobileConnectionModeAutoTitle = "Intelligens automata",
        MobileConnectionModeAutoDescription = "El\u0151sz\u00F6r a helyi kapcsolatot pr\u00F3b\u00E1lja, ha a telefon ugyanazon a h\u00E1l\u00F3zaton van, ut\u00E1na a publikus v\u00E9gpontot, v\u00E9g\u00FCl a cloud bridge-et.",
        MobileConnectionModeLocalTitle = "Helyi els\u0151",
        MobileConnectionModeLocalDescription = "A helyi API-t r\u00E9szes\u00EDti el\u0151nyben a g\u00E9p mellett, majd a direkt/publikus utat, v\u00E9g\u00FCl a cloud bridge-et.",
        MobileConnectionModeDirectTitle = "K\u00F6zvetlen internet",
        MobileConnectionModeDirectDescription = "A publikus v\u00E9gpontot vagy HTTPS alagutat prefer\u00E1lja. Ha ez nem v\u00E1laszol, cloud bridge-re v\u00E1lt.",
        MobileConnectionModeBridgeTitle = "Cloud bridge",
        MobileConnectionModeBridgeDescription = "Csak a szerver \u00E1ltal seg\u00EDtett kapcsolatot haszn\u00E1lja stabil internetes vagy neh\u00E9z NAT helyzetben.",
        MobileConnectionActiveUnknown = "Ismeretlen",
        MobileConnectionActiveLocal = "Helyi LAN",
        MobileConnectionActiveDirect = "K\u00F6zvetlen internet",
        MobileConnectionActiveBridge = "Cloud bridge",
        MobileConnectionLocalDetected = "Helyi h\u00E1l\u00F3zat \u00E9rz\u00E9kelve: a helyi API els\u0151k\u00E9nt pr\u00F3b\u00E1lhat\u00F3.",
        MobileConnectionLocalNotDetected = "A telefon nem t\u0171nik azonos helyi h\u00E1l\u00F3zaton l\u00E9v\u0151nek: a t\u00E1voli \u00FAtvonalak lesznek az els\u0151dleges fallbackek.",
        MobileConnectionEndpointMissing = "M\u00E9g nincs akt\u00EDv v\u00E9gpont.",
    };

    private static AppLanguageStrings CreateEnglish() => new()
    {
        CommonBack = "Back",
        CommonSave = "Save",
        CommonRefresh = "Refresh",
        CommonCancel = "Cancel",
        CommonConfirm = "Confirm",
        CommonClear = "Clear",
        CommonDelete = "Delete",
        DashboardSubtitle = "Local controller for raw milk vending",
        DashboardPromoPlaceholder = "Real images, video, or banners can be uploaded here later.",
        DashboardStatusTitle = "Controller status",
        DashboardStockTitle = "Current stock",
        DashboardTemperatureTitle = "Temperature",
        DashboardTemperatureSubtitle = "Continuous ESP32 monitoring",
        DashboardPriceTitle = "Price per liter",
        DashboardCreditTitle = "Current credit",
        DashboardPaymentCash = "Cash",
        DashboardPaymentCard = "Card",
        DashboardRequestedLitersTitle = "Selected quantity",
        DashboardSelectedTotalFormat = "Total: {0:0.00} RON",
        DashboardStockCapacityFormat = "of {0:0.##} L",
        DashboardContactFormat = "Operator contact: {0}",
        DashboardContactMissing = "Contact details not configured",
        DashboardStartDispense = "Start dispense",
        DashboardDispensingButton = "Dispensing...",
        DashboardStatusStarting = "Starting controller...",
        DashboardStatusCashSelected = "Cash payment is active. Quantity will follow the inserted credit.",
        DashboardStatusCardSelected = "Card payment is active. Select the desired quantity.",
        DashboardStatusDispenseStarted = "Dispensing has started.",
        DashboardStatusDispensing = "Milk is being dispensed. Please keep the bottle steady.",
        DashboardStatusCleaning = "The controller is running the cleaning cycle.",
        DashboardStatusCashBlocked = "Cash detected. Card payment is blocked for the current session.",
        DashboardStatusCashReady = "Cash payment is active. Insert banknotes and the quantity will be calculated automatically.",
        DashboardStatusReady = "Controller ready to serve.",
        DashboardAdminUnlockTitle = "Administrator access",
        DashboardAdminUnlockSubtitle = "Enter the numeric code to open the controller settings.",
        DashboardAdminUnlockPlaceholder = "Enter the access code",
        DashboardAdminUnlockInvalid = "Incorrect code. Please try again.",
        DashboardAdminChangeRequired = "Default code 1234 is blocked. Choose a new administrator code.",
        DashboardAdminChangeConfirm = "Confirm the new administrator code.",
        DashboardAdminChangeMismatch = "Codes do not match. Enter the new code again.",
        DashboardAdminChangeTooShort = "The new code must contain at least 4 digits.",
        DashboardAdminChangeDigitsOnly = "The new code can contain digits only.",
        DashboardAdminDefaultPasscodeBlocked = "Code 1234 can no longer be used.",
        SettingsTitle = "Controller settings",
        SettingsSalesTab = "Sales",
        SettingsGeneralSection = "General",
        SettingsSalesCardTitle = "Sales parameters",
        SettingsSalesCardDescription = "Configure the machine name, price, pulses per liter, and the stock currently available for sale.",
        SettingsAdminSection = "Administrator access",
        SettingsAdminCardDescription = "Change the secret code used for local settings access. Leave both fields empty if you do not want to modify it.",
        SettingsPaymentSection = "Payment and contact",
        SettingsPaymentCardDescription = "Enable the payment methods that should be visible to the customer on the main screen.",
        SettingsContactCardTitle = "Customer-facing contact details",
        SettingsContactCardDescription = "These details are shown on the vending screen so the customer can contact the operator.",
        SettingsValidatorSection = "Bill validator",
        SettingsValidatorCardDescription = "Configure the SSP/NV9 communication and how the controller decides whether a banknote should be accepted.",
        SettingsValidatorChannelsTitle = "Accepted banknotes",
        SettingsValidatorChannelsDescription = "Enable only the values that the validator should accept during the selling flow.",
        SettingsEsp32Section = "ESP32 and sensors",
        SettingsEsp32CardDescription = "Set the port and connection strategy for the ESP32 that reads sensors and controls the pump.",
        SettingsCleaningSection = "Cleaning",
        SettingsCleaningCardDescription = "Run the sanitation routines manually for the tubing and the pump.",
        SettingsUpdatesSection = "Updates",
        SettingsUpdatesCardDescription = "Shows which components can be updated from the local controller ecosystem.",
        SettingsUpdatesAvailableStatus = "Available",
        SettingsUpdatesControlTitle = "Control app",
        SettingsUpdatesControlDescription = "The tablet can receive a new control app update through a signed Android package.",
        SettingsUpdatesControlVersionFormat = "Current version: {0}",
        SettingsUpdatesEsp32Title = "ESP32 firmware",
        SettingsUpdatesEsp32Description = "The controller can send OTA firmware updates to the ESP32 through the serial flow and Wi-Fi network.",
        SettingsContinuousCleaningDescription = "Starts the pump continuously for a quick rinse of the line.",
        SettingsPulsedCleaningDescription = "Alternates pump on and off cycles for a more aggressive cleaning routine.",
        SettingsPairingSection = "Mobile app pairing",
        SettingsPairingCardDescription = "Configure the dispenser identity and the addresses used by the companion app on the local network or over the internet.",
        SettingsPairingSecurityHint = "The QR includes the unique machine ID, and the companion app receives a secure remote token after pairing.",
        SettingsPairingCodeTitle = "Pairing code",
        SettingsPairingEndpointTitle = "Primary companion endpoint",
        SettingsMachineIdLabel = "Unique machine ID",
        SettingsLocalApiBaseUrlLabel = "Local API address",
        SettingsPublicApiBaseUrlLabel = "Public API address",
        SettingsCloudApiBaseUrlLabel = "Cloud broker address",
        SettingsMachineNamePlaceholder = "Vending machine name",
        SettingsPricePlaceholder = "Price / liter",
        SettingsPulsesPlaceholder = "Pulses / liter",
        SettingsCurrentStockPlaceholder = "Current stock",
        SettingsTankCapacityPlaceholder = "Tank capacity",
        SettingsLowStockPlaceholder = "Low stock threshold",
        SettingsCashPayment = "Cash payment",
        SettingsCardPayment = "Card payment",
        SettingsContactPhonePlaceholder = "Contact phone",
        SettingsContactEmailPlaceholder = "Contact email",
        SettingsApiBaseUrlPlaceholder = "http://vendomat.local:1326",
        SettingsPublicApiBaseUrlPlaceholder = "https://milk-01.example.com",
        SettingsCloudApiBaseUrlPlaceholder = "https://vending.dllsoft.ro",
        SettingsValidatorEnabled = "Validator enabled",
        SettingsValidatorEscrow = "Host controlled escrow",
        SettingsBillPortLabel = "Validator port",
        SettingsBillBaudLabel = "Validator baud rate",
        SettingsBillPortPlaceholder = "/dev/ttyACM0",
        SettingsBillBaudPlaceholder = "115200",
        SettingsEsp32Enabled = "ESP32 enabled",
        SettingsEsp32AutoDiscover = "Port autodetect",
        SettingsRuntimeDemoMode = "Demo mode",
        SettingsRuntimeDemoModeHint = "Completes dispensing by simulation for test only, without ESP32 confirmation.",
        SettingsEsp32PortLabel = "ESP32 port",
        SettingsEsp32BaudLabel = "ESP32 baud rate",
        SettingsEsp32PortPlaceholder = "/dev/ttyS3",
        SettingsEsp32BaudPlaceholder = "115200",
        SettingsContinuousCleaning = "Continuous cleaning",
        SettingsPulsedCleaning = "Pulsed cleaning",
        SettingsGenerateQr = "Generate QR code",
        SettingsAdminPasscodePlaceholder = "New administrator password",
        SettingsAdminPasscodeConfirmPlaceholder = "Confirm new password",
        SettingsAdminPasscodeHint = "Leave both fields empty if you want to keep the current password.",
        SettingsPairingCodeFormat = "Code: {0}",
        SettingsPairingEndpointFormat = "Endpoint: {0}",
        SettingsSaveButton = "Save settings",
        SettingsLoadingStatus = "Loading controller settings...",
        SettingsReadyStatus = "Settings are ready for editing.",
        SettingsSavedStatus = "Settings were saved locally on the tablet.",
        SettingsAdminPasscodeUpdatedStatus = "Settings were saved and the administrator password was updated.",
        SettingsAdminPasscodeDigitsOnlyStatus = "The administrator password can contain digits only.",
        SettingsAdminPasscodeTooShortStatus = "The administrator password must contain at least 4 digits.",
        SettingsAdminPasscodeDefaultRejectedStatus = "Default password 1234 can no longer be used.",
        SettingsAdminPasscodeMismatchStatus = "The new password and confirmation do not match.",
        SettingsQrReadyStatus = "The pairing code is ready for the mobile app.",
        SettingsContinuousCleaningStatus = "Continuous cleaning has been executed.",
        SettingsPulsedCleaningStatus = "Pulsed cleaning has been executed.",
        MobileDevicesTitle = "My dispensers",
        MobileDevicesSubtitle = "Monitor and configure multiple milk vending machines from one app.",
        MobileAddDevice = "Add via QR",
        MobileDevicesEmptyTitle = "No paired dispenser",
        MobileDevicesEmptySubtitle = "Scan the QR code shown on the vending machine to add it to the app.",
        MobileDevicesOpenDashboard = "Dashboard",
        MobileDevicesOpenSettings = "Settings",
        MobileDevicesRemoveTitle = "Remove dispenser",
        MobileDevicesRemoveMessageFormat = "Do you want to remove \"{0}\" from the companion app?",
        MobileDevicesStatusOnline = "Online",
        MobileDevicesStatusOffline = "Offline",
        MobileDevicesLastSeenFormat = "Last update: {0:g}",
        MobileScannerTitle = "Scan QR code",
        MobileScannerSubtitle = "Point the camera at the code shown on the dispenser screen.",
        MobileScannerManualHint = "If scanning does not start, check camera permission.",
        MobileScannerManualModeTitle = "Manual pairing",
        MobileScannerManualModeHint = "Hidden test mode: fill the pairing fields or launch it through ADB.",
        MobileScannerManualOpenStatus = "Manual pairing mode is now open.",
        MobileScannerManualPairButton = "Pair manually",
        MobileScannerManualInvalidData = "Manual pairing data is incomplete or invalid.",
        MobileScannerInvalidQr = "The QR code does not contain a valid dispenser payload.",
        MobileScannerExpiredQr = "The QR code has expired. Generate a new one from the controller.",
        MobileScannerPermissionRequired = "Camera permission is required to scan the QR code.",
        MobileScannerConnectionError = "Could not reach the dispenser on any valid endpoint from the QR code, including the cloud broker.",
        MobileScannerPairSuccess = "The dispenser has been added to the app.",
        MobileScannerAlreadyAdded = "This dispenser is already in the app.",
        MobileDetailStatusTitle = "Current status",
        MobileDetailTemperatureTitle = "Temperature",
        MobileDetailStockTitle = "Stock",
        MobileDetailPriceTitle = "Price per liter",
        MobileDetailCreditTitle = "Current credit",
        MobileDetailPaymentTitle = "Active payment",
        MobileDetailStateTitle = "Activity",
        MobileDetailContactTitle = "Contact",
        MobileDetailApiBaseUrlTitle = "API",
        MobileDetailOpenSettings = "Open settings",
        MobileDetailRemoteCreditTitle = "Remote credit",
        MobileDetailRemoteCreditSubtitle = "Add credit to the current session directly from the companion app.",
        MobileDetailRemoteCreditButton = "Add credit",
        MobileDetailRemoteCreditInvalid = "Enter a valid amount for remote credit.",
        MobileDetailRemoteCreditError = "Could not add remote credit. Check the active endpoint and dispenser connection.",
        MobileDetailRemoteCreditQueued = "The command was sent through cloud and will be applied on the dispenser in a few seconds.",
        MobileDetailRunContinuousCleaning = "Continuous cleaning",
        MobileDetailRunPulsedCleaning = "Pulsed cleaning",
        MobileDetailUpdatedAtFormat = "Updated at {0:g}",
        MobileDetailSalesSectionTitle = "Sales",
        MobileDetailTodayRevenueTitle = "Revenue today",
        MobileDetailTodaySalesCountTitle = "Sales today",
        MobileDetailTotalRevenueTitle = "Total revenue",
        MobileDetailTotalSalesCountTitle = "Total transactions",
        MobileDetailRecentSalesTitle = "Recent sales",
        MobileDetailNoSalesHistory = "There are no saved sales for this dispenser yet.",
        MobileDetailSanitationSectionTitle = "Sanitation",
        MobileDetailLastSanitationTitle = "Last sanitation",
        MobileDetailSanitationCountTitle = "Cycles",
        MobileDetailRecentSanitationTitle = "Recent sanitation",
        MobileDetailNoSanitationHistory = "There are no saved sanitation cycles yet.",
        MobileDetailSaleStatusPending = "Pending",
        MobileDetailSaleStatusCompleted = "Completed",
        MobileDetailSaleStatusFailed = "Failed",
        MobileDetailSanitationContinuous = "Continuous cleaning",
        MobileDetailSanitationPulsed = "Pulsed cleaning",
        MobileDetailReady = "Ready",
        MobileDetailDispensing = "Dispensing",
        MobileDetailCleaning = "Cleaning",
        MobileDetailOutOfService = "Out of service",
        MobileDetailUnknown = "Unknown",
        MobileSettingsTitle = "Dispenser settings",
        MobileSettingsStatusLoading = "Loading device settings...",
        MobileSettingsStatusLoaded = "Remote settings are ready for editing.",
        MobileSettingsStatusSending = "Sending changes to the dispenser...",
        MobileSettingsStatusAwaitingDevice = "Waiting for the dispenser to confirm...",
        MobileSettingsStatusApplied = "The dispenser applied and confirmed the settings.",
        MobileSettingsStatusSaved = "Remote settings have been saved.",
        MobileSettingsStatusLoadError = "Could not load settings from the dispenser.",
        MobileSettingsStatusSaveError = "Could not save settings to the dispenser.",
        MobileConnectionSectionTitle = "Companion connection",
        MobileConnectionSectionSubtitle = "Choose how the phone should reach the dispenser and see the active route immediately.",
        MobileConnectionStrategyTitle = "Strategy",
        MobileConnectionActiveModeTitle = "Active route",
        MobileConnectionActiveEndpointTitle = "Active endpoint",
        MobileConnectionFallbackTitle = "Fallback order",
        MobileConnectionModeAutoTitle = "Smart auto",
        MobileConnectionModeAutoDescription = "Try the local connection first when the phone is on the same network, then the public endpoint, then the cloud bridge.",
        MobileConnectionModeLocalTitle = "Local first",
        MobileConnectionModeLocalDescription = "Prefer the local API near the dispenser, then try the direct/public route and finally the cloud bridge.",
        MobileConnectionModeDirectTitle = "Direct internet",
        MobileConnectionModeDirectDescription = "Prefer the public endpoint or HTTPS tunnel. If it does not respond, fall back to the cloud bridge.",
        MobileConnectionModeBridgeTitle = "Cloud bridge",
        MobileConnectionModeBridgeDescription = "Use only the server-assisted path when you need stable internet access or difficult NAT traversal.",
        MobileConnectionActiveUnknown = "Unknown",
        MobileConnectionActiveLocal = "Local LAN",
        MobileConnectionActiveDirect = "Direct internet",
        MobileConnectionActiveBridge = "Cloud bridge",
        MobileConnectionLocalDetected = "Local network detected: the local API can be tried first.",
        MobileConnectionLocalNotDetected = "The phone does not appear to be on the same local network: remote routes become the primary fallback.",
        MobileConnectionEndpointMissing = "No active endpoint yet.",
    };
}
